/**
 * seed.ts — starter curriculum.
 *
 * This is deliberately small but *real*: it is the bootstrapping content that makes
 * onboarding, SRS and mock mode work on day one without an API key. In production the
 * bulk of this is generated by the model at run time and validated against the
 * coverage gate in pedagogy.ts; here it seeds the frequency bands, the placement
 * probes and the scenario library.
 *
 * Levels use the JLPT↔CEFR reference mapping printed on score reports since Dec 2025.
 */

import type { CEFR } from '../types';

export interface SeedVocab {
  id: string; surface: string; reading: string; en: string;
  pos: 'noun' | 'verb' | 'i-adj' | 'na-adj' | 'adverb' | 'expression' | 'counter' | 'particle-phrase';
  level: CEFR; freqRank: number; example: string; exampleEN: string; tags: string[];
}
export interface SeedGrammar {
  id: string; level: CEFR; pattern: string; en: string; example: string; exampleEN: string;
  commonError: string; errorTag: string; tags: string[];
}
export interface SeedKanji {
  char: string; meaning: string; on: string[]; kun: string[]; level: CEFR; radical: string;
  mnemonic: string; words: { ja: string; reading: string; en: string }[];
}
export interface SeedCanDo {
  id: string; level: CEFR; skill: 'listening' | 'speaking' | 'reading' | 'writing' | 'interaction';
  statement: string; evidence: string;
}
export interface SeedScenario {
  id: string; title: string; titleEN: string; level: CEFR; setting: string;
  tutorRole: string; learnerRole: string; learnerGoal: string;
  items: string[]; register: 'casual' | 'polite' | 'keigo' | 'mixed'; mustDo: string[]; tags: string[];
}

export const VOCAB: SeedVocab[] = [
  { id: 'v.ohayou', surface: 'おはよう', reading: 'おはよう', en: 'good morning', pos: 'expression', level: 'A1', freqRank: 12, example: 'おはよう。今日も暑いね。', exampleEN: 'Morning. Hot again today, huh.', tags: ['greeting', 'chunk'] },
  { id: 'v.arigatou', surface: 'ありがとう', reading: 'ありがとう', en: 'thanks', pos: 'expression', level: 'A1', freqRank: 15, example: '手伝ってくれてありがとう。', exampleEN: 'Thanks for helping me.', tags: ['greeting', 'chunk'] },
  { id: 'v.sumimasen', surface: 'すみません', reading: 'すみません', en: 'excuse me / sorry', pos: 'expression', level: 'A1', freqRank: 18, example: 'すみません、ちょっといいですか。', exampleEN: 'Excuse me, do you have a moment?', tags: ['chunk', 'repair', 'high_value'] },
  { id: 'v.onegaishimasu', surface: 'お願いします', reading: 'おねがいします', en: 'please (request)', pos: 'expression', level: 'A1', freqRank: 20, example: 'コーヒーをお願いします。', exampleEN: 'A coffee, please.', tags: ['chunk', 'service', 'high_value'] },
  { id: 'v.eki', surface: '駅', reading: 'えき', en: 'station', pos: 'noun', level: 'A1', freqRank: 30, example: '駅まで歩いて五分です。', exampleEN: "It's a five-minute walk to the station.", tags: ['place', 'travel'] },
  { id: 'v.takusan', surface: 'たくさん', reading: 'たくさん', en: 'a lot', pos: 'adverb', level: 'A1', freqRank: 40, example: '本をたくさん読みました。', exampleEN: 'I read a lot of books.', tags: ['quantity'] },
  { id: 'v.genki', surface: '元気', reading: 'げんき', en: 'healthy / lively', pos: 'na-adj', level: 'A1', freqRank: 45, example: '最近、元気ですか。', exampleEN: 'How have you been lately?', tags: ['state'] },
  { id: 'v.mouichido', surface: 'もう一度', reading: 'もういちど', en: 'one more time', pos: 'expression', level: 'A1', freqRank: 60, example: 'すみません、もう一度お願いします。', exampleEN: 'Sorry, could you say that again?', tags: ['repair', 'high_value', 'chunk'] },
  { id: 'v.wakaru', surface: '分かる', reading: 'わかる', en: 'to understand', pos: 'verb', level: 'A1', freqRank: 22, example: 'ゆっくり言えば分かります。', exampleEN: 'If you speak slowly, I understand.', tags: ['state', 'verb'] },
  { id: 'v.matsu', surface: '待つ', reading: 'まつ', en: 'to wait', pos: 'verb', level: 'A1', freqRank: 55, example: 'ここで待っててください。', exampleEN: 'Please wait here.', tags: ['verb', 'service'] },
  { id: 'v.tsukau', surface: '使う', reading: 'つかう', en: 'to use', pos: 'verb', level: 'A1', freqRank: 35, example: 'Suicaを使ってもいいですか。', exampleEN: 'Can I use Suica?', tags: ['verb', 'transitive'] },
  { id: 'v.denwa', surface: '電話', reading: 'でんわ', en: 'phone / phone call', pos: 'noun', level: 'A2.1', freqRank: 48, example: '後で電話をかけます。', exampleEN: 'I will call you later.', tags: ['collocation', 'noun'] },
  { id: 'v.yoyaku', surface: '予約', reading: 'よやく', en: 'reservation', pos: 'noun', level: 'A2.1', freqRank: 70, example: '席を予約しておきます。', exampleEN: "I'll reserve a seat.", tags: ['service', 'noun', 'high_value'] },
  { id: 'v.riyou', surface: '利用', reading: 'りよう', en: 'use / utilisation', pos: 'noun', level: 'A2.1', freqRank: 90, example: 'このアプリを利用しています。', exampleEN: 'I use this app.', tags: ['formal', 'noun'] },
  { id: 'v.tetsudau', surface: '手伝う', reading: 'てつだう', en: 'to help out', pos: 'verb', level: 'A2.1', freqRank: 80, example: '引っ越しを手伝ってくれてありがとう。', exampleEN: 'Thanks for helping me move.', tags: ['verb', 'social'] },
  { id: 'v.byouin', surface: '病院', reading: 'びょういん', en: 'hospital / clinic', pos: 'noun', level: 'A2.1', freqRank: 85, example: '病院へ行ったほうがいいですよ。', exampleEN: 'You should go to a clinic.', tags: ['health', 'noun', 'high_value'] },
  { id: 'v.asagohan', surface: '朝ごはん', reading: 'あさごはん', en: 'breakfast', pos: 'noun', level: 'A1', freqRank: 75, example: '朝ごはんはパンと卵です。', exampleEN: 'Breakfast is bread and eggs.', tags: ['food', 'noun'] },
  { id: 'v.tanomu', surface: '頼む', reading: 'たのむ', en: 'to request / to order', pos: 'verb', level: 'A2.1', freqRank: 95, example: 'これを頼んでいい？', exampleEN: 'Can I order this?', tags: ['verb', 'service'] },
  { id: 'v.kansha', surface: '感謝します', reading: 'かんしゃします', en: 'I am grateful', pos: 'verb', level: 'B1', freqRank: 300, example: 'ご協力に感謝します。', exampleEN: 'I appreciate your cooperation.', tags: ['formal', 'business'] },
  { id: 'v.kakunin', surface: '確認', reading: 'かくにん', en: 'to confirm / check', pos: 'noun', level: 'B1', freqRank: 140, example: '内容を確認のうえ、返信します。', exampleEN: "I'll check the details and reply.", tags: ['business', 'high_value', 'noun'] },
  { id: 'v.taiou', surface: '対応', reading: 'たいおう', en: 'to handle / deal with', pos: 'noun', level: 'B1', freqRank: 160, example: 'クレームの対応をしています。', exampleEN: "I'm handling a complaint.", tags: ['business', 'noun'] },
  { id: 'v.hitsuyou', surface: '必要', reading: 'ひつよう', en: 'necessary', pos: 'na-adj', level: 'B1', freqRank: 130, example: '予約は必要ですか。', exampleEN: 'Is a reservation necessary?', tags: ['abstract', 'na-adj'] },
  { id: 'v.muri', surface: '無理', reading: 'むり', en: 'impossible / unreasonable', pos: 'na-adj', level: 'B1', freqRank: 120, example: '申し訳ありませんが、それは無理です。', exampleEN: "I'm sorry, but that's not possible.", tags: ['refusal', 'high_value', 'keigo'] },
  { id: 'v.henko', surface: '変更', reading: 'へんこう', en: 'change / alteration', pos: 'noun', level: 'B1', freqRank: 175, example: '予約の変更をお願いできますか。', exampleEN: 'Could I change my reservation?', tags: ['business', 'noun'] },
  { id: 'v.saisho', surface: '最初', reading: 'さいしょ', en: 'first / at first', pos: 'noun', level: 'B1', freqRank: 150, example: '最初は難しかったけど、慣れました。', exampleEN: 'It was hard at first, but I got used to it.', tags: ['discourse'] },
  { id: 'v.kikkake', surface: 'きっかけ', reading: 'きっかけ', en: 'trigger / reason for starting', pos: 'noun', level: 'B2', freqRank: 320, example: 'アニメが日本語を始めたきっかけです。', exampleEN: 'Anime is what got me started on Japanese.', tags: ['opinion', 'noun', 'high_value'] },
  { id: 'v.~baai', surface: '場合', reading: 'ばあい', en: 'case / situation', pos: 'noun', level: 'B2', freqRank: 260, example: '遅れる場合は連絡してください。', exampleEN: 'If you are going to be late, please get in touch.', tags: ['formal', 'noun'] },
  { id: 'v.nioujite', surface: '〜に応じて', reading: '〜におうじて', en: 'according to / depending on', pos: 'expression', level: 'B2', freqRank: 400, example: 'レベルに応じて内容を変えます。', exampleEN: 'The content changes according to level.', tags: ['formal', 'grammar-chunk'] },
  { id: 'v.kaizen', surface: '改善', reading: 'かいぜん', en: 'improvement', pos: 'noun', level: 'B2', freqRank: 350, example: '業務の改善を提案しました。', exampleEN: 'I proposed a workflow improvement.', tags: ['business', 'noun'] },
  { id: 'v.zannen', surface: '残念', reading: 'ざんねん', en: 'regrettable / a shame', pos: 'na-adj', level: 'B1', freqRank: 165, example: 'それは残念ですね。', exampleEN: 'That is a shame.', tags: ['reaction', 'na-adj'] },
  { id: 'v.omoshiroi', surface: '面白い', reading: 'おもしろい', en: 'interesting / funny', pos: 'i-adj', level: 'A1', freqRank: 65, example: '面白い話を聞きました。', exampleEN: 'I heard an interesting story.', tags: ['opinion', 'i-adj'] },
  { id: 'v.muzukashii', surface: '難しい', reading: 'むずかしい', en: 'difficult', pos: 'i-adj', level: 'A1', freqRank: 68, example: '敬語はまだ難しいです。', exampleEN: 'Keigo is still difficult for me.', tags: ['opinion', 'i-adj'] },
  { id: 'v.nareru', surface: '慣れる', reading: 'なれる', en: 'to get used to', pos: 'verb', level: 'B1', freqRank: 190, example: '日本の生活に慣れてきました。', exampleEN: "I've been getting used to life in Japan.", tags: ['verb', 'experience'] },
  { id: 'v.tokuni', surface: '特に', reading: 'とくに', en: 'especially', pos: 'adverb', level: 'B1', freqRank: 145, example: '特に文法が苦手です。', exampleEN: "Grammar is especially my weak point.", tags: ['discourse'] },
  { id: 'v.otsukaresama', surface: 'お疲れさまです', reading: 'おつかれさまです', en: 'thanks for your hard work', pos: 'expression', level: 'B1', freqRank: 110, example: 'お疲れさまです。先に失礼します。', exampleEN: "Good work today — I'll head off first.", tags: ['workplace', 'chunk', 'high_value'] },
  { id: 'v.osewa', surface: 'お世話になっております', reading: 'おせわになっております', en: 'thank you for your continued support (biz)', pos: 'expression', level: 'B2', freqRank: 210, example: 'いつもお世話になっております。', exampleEN: 'Thank you, as always, for your support.', tags: ['business', 'chunk', 'high_value', 'keigo'] },
];

export const GRAMMAR: SeedGrammar[] = [
  { id: 'g.desu', level: 'A1', pattern: 'N は N です', en: 'X is Y (polite)', example: '私は会社員です。', exampleEN: 'I am an office worker.', commonError: 'Mixing だ and です in one turn.', errorTag: 'verb.politeness', tags: ['copula'] },
  { id: 'g.masu', level: 'A1', pattern: 'V-ます / V-ません', en: 'polite present/negative', example: '毎日、日本語を勉強します。', exampleEN: 'I study Japanese every day.', commonError: 'Using dictionary form with strangers.', errorTag: 'verb.politeness', tags: ['politeness'] },
  { id: 'g.mashita', level: 'A1', pattern: 'V-ました / V-ませんでした', en: 'polite past', example: '昨日、映画を見ました。', exampleEN: 'I watched a film yesterday.', commonError: 'Dropping the past tense when a time word implies it.', errorTag: 'tense.past', tags: ['tense'] },
  { id: 'g.wo', level: 'A1', pattern: 'N を V', en: 'direct object', example: '水を飲みます。', exampleEN: 'I drink water.', commonError: 'Using は for the object; dropping を when the verb needs it.', errorTag: 'particle.wo_drop', tags: ['particle'] },
  { id: 'g.ni_de', level: 'A1', pattern: 'N に / N で', en: 'destination vs location of action', example: '学校に行って、図書館で勉強します。', exampleEN: 'I go to school and study at the library.', commonError: 'に where the action happens, で for destinations.', errorTag: 'particle.ni_de', tags: ['particle', 'high_value'] },
  { id: 'g.te_form', level: 'A2.1', pattern: 'V-て + V', en: 'sequencing and requests', example: '駅まで歩いて、電車に乗ります。', exampleEN: 'I walk to the station and get on the train.', commonError: 'Forming て-form by rule-of-thumb instead of sound group.', errorTag: 'verb.te_form', tags: ['conjugation', 'core'] },
  { id: 'g.te_kudasai', level: 'A2.1', pattern: 'V-てください / V-てもいいですか', en: 'requests and permission', example: 'ここに座ってもいいですか。', exampleEN: 'May I sit here?', commonError: 'Over-politeness where お願いします is more natural.', errorTag: 'verb.politeness', tags: ['service', 'high_value'] },
  { id: 'g.teimasu', level: 'A2.1', pattern: 'V-ています', en: 'progressive / resulting state', example: '今、友だちを待っています。', exampleEN: "I'm waiting for a friend right now.", commonError: 'Using ています for states like 知っています in the past.', errorTag: 'verb.aspect.teiru', tags: ['aspect', 'core'] },
  { id: 'g.tai', level: 'A2.1', pattern: 'V-たいです', en: 'want to do', example: '日本で働きたいです。', exampleEN: 'I want to work in Japan.', commonError: 'V-たい with someone else as the subject.', errorTag: 'verb.politeness', tags: ['desire'] },
  { id: 'g.koto_ga_dekimasu', level: 'A2.1', pattern: 'V-ることができます', en: 'can do', example: '少し日本語を話すことができます。', exampleEN: 'I can speak a little Japanese.', commonError: 'の instead of こと after abstract verbs.', errorTag: 'nominalizer.no_koto', tags: ['ability'] },
  { id: 'g.to_omoimasu', level: 'A2', pattern: '〜と思います', en: 'I think that…', example: '来年、日本に行こうと思います。', exampleEN: 'I think I will go to Japan next year.', commonError: 'Quoting with を instead of the plain form + と.', errorTag: 'wordorder', tags: ['opinion', 'high_value'] },
  { id: 'g.ta_koto_ga_aru', level: 'A2', pattern: 'V-たことがある', en: 'have done before', example: '京都に行ったことがあります。', exampleEN: 'I have been to Kyoto.', commonError: 'Plain past without こと before がある.', errorTag: 'wordorder', tags: ['experience'] },
  { id: 'g.tari_tari', level: 'A2', pattern: 'V-たり、V-たり', en: 'listing representative actions', example: '週末は本を読んだり、散歩したりします。', exampleEN: 'On weekends I read, take walks, and so on.', commonError: 'Forgetting the final します.', errorTag: 'wordorder', tags: ['listing'] },
  { id: 'g.nagara', level: 'B1', pattern: 'V-ながら', en: 'while doing', example: '音楽を聞きながら仕事をします。', exampleEN: 'I work while listening to music.', commonError: 'Using it with verbs of different subjects.', errorTag: 'wordorder', tags: ['clause'] },
  { id: 'g.youni', level: 'B1', pattern: '〜ように / 〜ようになる', en: 'so that / come to be able to', example: '毎日練習して、話せるようになりました。', exampleEN: 'I practised daily and became able to speak.', commonError: 'ように vs ために: intention vs change of state.', errorTag: 'conditional.forms', tags: ['clause', 'high_value'] },
  { id: 'g.ba', level: 'B1', pattern: 'V-ば / V-たら', en: 'conditional', example: '安ければ買います。', exampleEN: "If it's cheap, I'll buy it.", commonError: 'ば with い-adj: 安いば ✗ → 安ければ ✓', errorTag: 'conditional.forms', tags: ['conditional', 'high_value'] },
  { id: 'g.no_de', level: 'B1', pattern: '〜ので / 〜のに', en: 'because / although (soft)', example: '雨が降っているので、家にいます。', exampleEN: "It's raining, so I'll stay home.", commonError: 'ので with a noun needs な: 学生なので.', errorTag: 'wordorder', tags: ['connective'] },
  { id: 'g.koto_ni_suru', level: 'B1', pattern: 'V-ことにしています / ことになりました', en: 'habitual decision / something was decided', example: '毎朝六時に起きることにしています。', exampleEN: 'I make a point of getting up at six.', commonError: 'Confusing personal habit with organisational decision.', errorTag: 'aspect.teiru', tags: ['habit'] },
  { id: 'g.saseru', level: 'B1', pattern: 'V-させる / V-させられる', en: 'causative / causative-passive', example: '部長は私に資料を作らせた。', exampleEN: 'The director made me prepare the documents.', commonError: 'Causative without the に marked party.', errorTag: 'passive.causative', tags: ['voice', 'workplace'] },
  { id: 'g.ukemi', level: 'B1', pattern: 'V-られる (受身)', en: 'passive, incl. adversity passive', example: '電車の中で足を踏まれました。', exampleEN: 'My foot got stepped on in the train.', commonError: 'Avoiding the adversity passive, which is very natural in Japanese.', errorTag: 'passive.causative', tags: ['voice'] },
  { id: 'g.keigo_sonkei', level: 'B2', pattern: 'お-V-になります / いらっしゃる', en: 'respectful (for others)', example: '部長はもう会議にいらっしゃいます。', exampleEN: 'The director is already at the meeting.', commonError: 'Mixing 尊敬語 and 謙譲語 for the same person.', errorTag: 'keigo.honorific', tags: ['keigo', 'high_value', 'workplace'] },
  { id: 'g.keigo_kenjou', level: 'B2', pattern: 'お-V-します / 伺う / 申し上げる', en: 'humble (for self)', example: '明日、私が伺います。', exampleEN: 'I will visit tomorrow.', commonError: 'Using 参る for a customer\'s movement.', errorTag: 'keigo.humble', tags: ['keigo', 'high_value', 'workplace'] },
  { id: 'g.wake_dewa_nai', level: 'B2', pattern: '〜わけではない', en: 'it is not that…', example: '嫌いなわけではありません。', exampleEN: "It's not that I dislike it.", commonError: 'Blunt partial negation without わけ/とは限らない softeners.', errorTag: 'conditional.forms', tags: ['nuance'] },
  { id: 'g.ni_taishite', level: 'B2', pattern: '〜に対して / 〜につき', en: 'towards / owing to (formal)', example: 'お客様に対して失礼な態度は許されません。', exampleEN: 'Rudeness towards customers is not tolerated.', commonError: 'Register: these belong in writing, not casual speech.', errorTag: 'verb.politeness', tags: ['formal', 'business'] },
];

export const KANJI: SeedKanji[] = [
  { char: '日', meaning: 'sun, day', on: ['ニチ', 'ジツ'], kun: ['ひ', 'び', 'か'], level: 'A1', radical: '日', mnemonic: 'A window with a line through it — the sun behind it.', words: [{ ja: '日本', reading: 'にほん', en: 'Japan' }, { ja: '毎日', reading: 'まいにち', en: 'every day' }] },
  { char: '本', meaning: 'book, origin', on: ['ホン'], kun: ['もと'], level: 'A1', radical: '木', mnemonic: 'A tree (木) with a line marking its root — the origin.', words: [{ ja: '本', reading: 'ほん', en: 'book' }, { ja: '日本', reading: 'にほん', en: 'Japan' }] },
  { char: '人', meaning: 'person', on: ['ジン', 'ニン'], kun: ['ひと'], level: 'A1', radical: '人', mnemonic: 'Two legs walking — a person.', words: [{ ja: '日本人', reading: 'にほんじん', en: 'Japanese person' }, { ja: '三人', reading: 'さんにん', en: 'three people' }] },
  { char: '水', meaning: 'water', on: ['スイ'], kun: ['みず'], level: 'A1', radical: '水', mnemonic: 'A splash of droplets around a central stream.', words: [{ ja: '水', reading: 'みず', en: 'water' }, { ja: '水曜日', reading: 'すいようび', en: 'Wednesday' }] },
  { char: '月', meaning: 'moon, month', on: ['ゲツ', 'ガツ'], kun: ['つき'], level: 'A1', radical: '月', mnemonic: 'A crescent with two extra strokes — a moon phase.', words: [{ ja: '月曜日', reading: 'げつようび', en: 'Monday' }, { ja: '一月', reading: 'いちがつ', en: 'January' }] },
  { char: '火', meaning: 'fire', on: ['カ'], kun: ['ひ'], level: 'A1', radical: '火', mnemonic: 'A person (人) with sparks flying off — standing in flames.', words: [{ ja: '火曜日', reading: 'かようび', en: 'Tuesday' }, { ja: '花火', reading: 'はなび', en: 'fireworks' }] },
  { char: '山', meaning: 'mountain', on: ['サン'], kun: ['やま'], level: 'A1', radical: '山', mnemonic: 'Three peaks rising from a base line.', words: [{ ja: '山', reading: 'やま', en: 'mountain' }, { ja: '富士山', reading: 'ふじさん', en: 'Mt Fuji' }] },
  { char: '川', meaning: 'river', on: ['セン'], kun: ['かわ'], level: 'A1', radical: '川', mnemonic: 'Two banks with water flowing between them.', words: [{ ja: '川', reading: 'かわ', en: 'river' }, { ja: '小川', reading: 'おがわ', en: 'stream' }] },
  { char: '食', meaning: 'eat, food', on: ['ショク'], kun: ['たべる', 'くう'], level: 'A1', radical: '食', mnemonic: 'A roof over a good (良) meal.', words: [{ ja: '食べる', reading: 'たべる', en: 'to eat' }, { ja: '食べ物', reading: 'たべもの', en: 'food' }] },
  { char: '飲', meaning: 'drink', on: ['イン'], kun: ['のむ'], level: 'A1', radical: '食', mnemonic: 'Food radical on the left, a person yawning (欠) on the right.', words: [{ ja: '飲む', reading: 'のむ', en: 'to drink' }, { ja: '飲み物', reading: 'のみもの', en: 'a drink' }] },
  { char: '見', meaning: 'see', on: ['ケン'], kun: ['みる'], level: 'A1', radical: '見', mnemonic: 'An eye on legs — looking around.', words: [{ ja: '見る', reading: 'みる', en: 'to see' }, { ja: '花見', reading: 'はなみ', en: 'cherry-blossom viewing' }] },
  { char: '行', meaning: 'go', on: ['コウ', 'ギョウ'], kun: ['いく', 'おこなう'], level: 'A1', radical: '行', mnemonic: 'A crossroads with footsteps leading away.', words: [{ ja: '行く', reading: 'いく', en: 'to go' }, { ja: '銀行', reading: 'ぎんこう', en: 'bank' }] },
  { char: '買', meaning: 'buy', on: ['バイ'], kun: ['かう'], level: 'A2.1', radical: '貝', mnemonic: 'A net (罒) over a shell (貝) — shells were money; you are buying.', words: [{ ja: '買う', reading: 'かう', en: 'to buy' }, { ja: '買い物', reading: 'かいもの', en: 'shopping' }] },
  { char: '駅', meaning: 'station', on: ['エキ'], kun: [], level: 'A2.1', radical: '馬', mnemonic: 'Horse radical — in the old days, a station was where you changed horses.', words: [{ ja: '駅', reading: 'えき', en: 'station' }, { ja: '東京駅', reading: 'とうきょうえき', en: 'Tokyo Station' }] },
  { char: '電', meaning: 'electricity', on: ['デン'], kun: [], level: 'A2.1', radical: '雨', mnemonic: 'Rain (雨) over a field — lightning and electricity.', words: [{ ja: '電車', reading: 'でんしゃ', en: 'train' }, { ja: '電話', reading: 'でんわ', en: 'telephone' }] },
  { char: '話', meaning: 'speak, story', on: ['ワ'], kun: ['はなす', 'はなし'], level: 'A2.1', radical: '言', mnemonic: 'Speech radical plus tongue (舌) = talk.', words: [{ ja: '話す', reading: 'はなす', en: 'to speak' }, { ja: '電話', reading: 'でんわ', en: 'telephone' }] },
  { char: '読', meaning: 'read', on: ['ドク'], kun: ['よむ'], level: 'A2.1', radical: '言', mnemonic: 'Speech radical with a seller (売) — reading out a sales pitch.', words: [{ ja: '読む', reading: 'よむ', en: 'to read' }, { ja: '読書', reading: 'どくしょ', en: 'reading (as a hobby)' }] },
  { char: '書', meaning: 'write', on: ['ショ'], kun: ['かく'], level: 'A2.1', radical: '曰', mnemonic: 'A hand (聿) with a brush, writing on a surface (曰).', words: [{ ja: '書く', reading: 'かく', en: 'to write' }, { ja: '図書館', reading: 'としょかん', en: 'library' }] },
  { char: '質', meaning: 'quality, substance', on: ['シツ'], kun: [], level: 'B1', radical: '貝', mnemonic: 'Shell/money plus an axe — you pay for quality.', words: [{ ja: '質問', reading: 'しつもん', en: 'a question' }, { ja: '品質', reading: 'ひんしつ', en: 'quality' }] },
  { char: '問', meaning: 'question', on: ['モン'], kun: ['とう'], level: 'B1', radical: '門', mnemonic: 'A gate (門) you must speak (口) at to be let through.', words: [{ ja: '質問', reading: 'しつもん', en: 'question' }, { ja: '問題', reading: 'もんだい', en: 'problem' }] },
  { char: '確', meaning: 'certain, confirm', on: ['カク'], kun: ['たしか', 'たしかめる'], level: 'B1', radical: '石', mnemonic: 'Stone (石) solid — certainty.', words: [{ ja: '確認', reading: 'かくにん', en: 'confirmation' }, { ja: '確か', reading: 'たしか', en: 'if I recall correctly' }] },
  { char: '認', meaning: 'recognise, acknowledge', on: ['ニン'], kun: ['みとめる'], level: 'B1', radical: '言', mnemonic: 'Speech radical plus endurance (忍) — admitting something you would rather not.', words: [{ ja: '確認', reading: 'かくにん', en: 'confirmation' }, { ja: '認める', reading: 'みとめる', en: 'to acknowledge' }] },
  { char: '経', meaning: 'pass through, manage', on: ['ケイ'], kun: ['へる'], level: 'B2', radical: '糸', mnemonic: 'Thread (糸) running through — a course, experience.', words: [{ ja: '経験', reading: 'けいけん', en: 'experience' }, { ja: '経済', reading: 'けいざい', en: 'economics' }] },
  { char: '験', meaning: 'test, effect', on: ['ケン'], kun: [], level: 'B2', radical: '馬', mnemonic: 'Horse radical — you used to be tested on horseback riding.', words: [{ ja: '経験', reading: 'けいけん', en: 'experience' }, { ja: '試験', reading: 'しけん', en: 'exam' }] },
];

export const CANDO: SeedCanDo[] = [
  { id: 'c.a1.greet', level: 'A1', skill: 'speaking', statement: 'I can greet someone, say my name and where I am from, and ask theirs.', evidence: 'free' },
  { id: 'c.a1.order', level: 'A1', skill: 'speaking', statement: 'I can order food or drink at a counter and ask the price.', evidence: 'roleplay' },
  { id: 'c.a1.time', level: 'A1', skill: 'listening', statement: 'I can understand simple questions about time, place and price.', evidence: 'listening' },
  { id: 'c.a1.kana', level: 'A1', skill: 'reading', statement: 'I can read hiragana and katakana at sight, at roughly 1 kana per second.', evidence: 'timed' },
  { id: 'c.a1.sign', level: 'A1', skill: 'reading', statement: 'I can pick out familiar words on signs: 入口, 出口, 押す, 引く.', evidence: 'reading' },
  { id: 'c.a2.1.direction', level: 'A2.1', skill: 'interaction', statement: 'I can ask for directions and understand a two-step answer.', evidence: 'roleplay' },
  { id: 'c.a2.1.reserve', level: 'A2.1', skill: 'speaking', statement: 'I can make, change and cancel a reservation politely.', evidence: 'roleplay' },
  { id: 'c.a2.1.daily', level: 'A2.1', skill: 'speaking', statement: 'I can describe my day and week in a few connected sentences.', evidence: 'open_ended' },
  { id: 'c.a2.1.form', level: 'A2.1', skill: 'reading', statement: 'I can fill in a simple form with my details.', evidence: 'writing' },
  { id: 'c.a2.1.missed', level: 'A2.1', skill: 'interaction', statement: 'I can ask someone to repeat or explain when I do not understand.', evidence: 'free' },
  { id: 'c.a2.shop', level: 'A2', skill: 'interaction', statement: 'I can return an item and explain the problem.', evidence: 'roleplay' },
  { id: 'c.a2.opinion', level: 'A2', skill: 'speaking', statement: 'I can give a simple opinion and a reason for it.', evidence: 'open_ended' },
  { id: 'c.b1.workplace', level: 'B1', skill: 'listening', statement: 'I can follow the main points of a work meeting and note the action items.', evidence: 'listening' },
  { id: 'c.b1.keigo', level: 'B1', skill: 'speaking', statement: 'I can use basic 敬語 with a customer or senior colleague without switching register mid-sentence.', evidence: 'roleplay' },
  { id: 'c.b1.complaint', level: 'B1', skill: 'interaction', statement: 'I can complain about a problem and stay polite while being firm.', evidence: 'roleplay' },
  { id: 'c.b1.summary', level: 'B1', skill: 'writing', statement: 'I can write a short, clear email or message to a colleague.', evidence: 'writing' },
  { id: 'c.b2.meeting', level: 'B2', skill: 'speaking', statement: 'I can disagree with a proposal in a meeting and offer an alternative.', evidence: 'open_ended' },
  { id: 'c.b2.article', level: 'B2', skill: 'reading', statement: 'I can read a newspaper article and summarise its argument.', evidence: 'reading' },
  { id: 'c.b2.negotiate', level: 'B2', skill: 'interaction', statement: 'I can negotiate a deadline or a price and hold my position politely.', evidence: 'roleplay' },
  { id: 'c.b2.nuance', level: 'B2', skill: 'listening', statement: 'I can tell when a Japanese speaker is politely refusing rather than agreeing.', evidence: 'listening' },
];

export const SCENARIOS: SeedScenario[] = [
  { id: 's.conbini', title: 'コンビニで', titleEN: 'At the convenience store', level: 'A1', setting: 'A convenience store in Shinjuku, 11pm.', tutorRole: 'store clerk', learnerRole: 'hungry customer', learnerGoal: 'Buy onigiri, get it heated, and add a hot drink.', items: ['v.onegaishimasu', 'v.sumimasen', 'v.genki'], register: 'polite', mustDo: ['Use お願いします for each request', 'Answer one yes/no question'], tags: ['travel', 'service', 'survival'] },
  { id: 's.ramen', title: 'ラーメン屋で', titleEN: 'At a ramen shop', level: 'A1+', setting: 'A busy ramen shop with a ticket machine outside.', tutorRole: 'shop staff', learnerRole: 'first-time customer', learnerGoal: 'Order, choose noodle firmness and spiciness, and ask where to sit.', items: ['v.sumimasen', 'v.takusan'], register: 'polite', mustDo: ['Order with the right counter or set phrase', 'Ask one question with 〜はありますか'], tags: ['food', 'travel', 'survival'] },
  { id: 's.eki', title: '駅で道を聞く', titleEN: 'Asking directions at the station', level: 'A2.1', setting: 'Shinjuku station, you cannot find the JR Yamanote line.', tutorRole: 'station attendant', learnerRole: 'lost traveller', learnerGoal: 'Understand a two-step direction and confirm you got it right.', items: ['v.eki', 'v.mouichido'], register: 'polite', mustDo: ['Ask for directions', 'Repeat back the route to confirm (〜ですね)'], tags: ['travel', 'interaction', 'high_value'] },
  { id: 's.clinic', title: 'クリニックで', titleEN: 'At the clinic', level: 'A2.1', setting: 'A small clinic; you have had a fever for three days.', tutorRole: 'nurse at reception', learnerRole: 'patient', learnerGoal: 'Describe symptoms, answer duration questions, and book a follow-up.', items: ['v.byouin', 'v.yoyaku'], register: 'polite', mustDo: ['Describe a symptom and how long', 'Give your details when asked'], tags: ['health', 'high_value', 'survival'] },
  { id: 's.hotel', title: 'ホテルの予約変更', titleEN: 'Changing a hotel booking', level: 'B1', setting: 'Phone call to a business hotel.', tutorRole: 'hotel front desk', learnerRole: 'guest changing dates', learnerGoal: 'Move the booking two days later and confirm the new price.', items: ['v.henko', 'v.yoyaku', 'v.muri'], register: 'keigo', mustDo: ['Use 〜をお願いできますか', 'Confirm dates back to them'], tags: ['travel', 'business', 'high_value'] },
  { id: 's.interview', title: 'アルバイトの面接', titleEN: 'Part-time job interview', level: 'B1', setting: 'A café interview, 10 minutes.', tutorRole: 'café manager', learnerRole: 'applicant', learnerGoal: 'Explain availability, experience, and why you want the job.', items: ['v.taiou', 'v.kanri'], register: 'keigo', mustDo: ['Give a reason with 〜ので', 'Answer about availability with specific days'], tags: ['work', 'high_value', 'jlpt'] },
  { id: 's.office', title: '職場の朝', titleEN: 'Morning at the office', level: 'B1', setting: 'Monday morning in a Tokyo office.', tutorRole: 'senior colleague', learnerRole: 'new team member', learnerGoal: 'Give a status update, ask for a deadline extension, and greet properly.', items: ['v.otsukaresama', 'v.kakunin'], register: 'mixed', mustDo: ['Use お疲れさまです appropriately', 'Ask for an extension politely'], tags: ['work', 'keigo', 'high_value'] },
  { id: 's.complaint', title: 'クレーム対応', titleEN: 'Handling a complaint', level: 'B2', setting: 'A customer calls angry about a broken delivery.', tutorRole: 'customer', learnerRole: 'support staff', learnerGoal: 'Acknowledge, apologise without over-promising, and offer a concrete fix.', items: ['v.taiou', 'v.muri', 'v.kaizen'], register: 'keigo', mustDo: ['Use humble forms for your own actions', 'Give a concrete next step'], tags: ['work', 'keigo', 'high_value'] },
  { id: 's.meeting', title: '会議で反対する', titleEN: 'Disagreeing in a meeting', level: 'B2', setting: 'A planning meeting; a proposal has a flaw.', tutorRole: 'project lead', learnerRole: 'team member', learnerGoal: 'Disagree with the schedule and propose an alternative, without sounding blunt.', items: ['v.muri', 'v.kakunin'], register: 'keigo', mustDo: ['Soften first (〜のですが)', 'Offer an alternative, not just a no'], tags: ['work', 'nuance', 'high_value'] },
  { id: 's.friend', title: '友だちと週末の話', titleEN: 'Weekend chat with a friend', level: 'A2', setting: 'A café on Saturday.', tutorRole: 'close friend', learnerRole: 'friend', learnerGoal: 'Chat casually about your weekend and ask about theirs.', items: ['v.omoshiroi', 'v.takusan'], register: 'casual', mustDo: ['Use plain form, not ます', 'Ask at least two follow-up questions'], tags: ['social', 'fluency', 'casual'] },
  { id: 's.inlaws', title: '義理の父母との会話', titleEN: 'Chatting with your partner’s parents', level: 'B1', setting: 'A family dinner with your partner’s parents.', tutorRole: 'partner’s mother', learnerRole: 'partner', learnerGoal: 'Be polite, humble about yourself, and keep the conversation alive.', items: ['v.muzukashii', 'v.nareru'], register: 'keigo', mustDo: ['Use humble forms about yourself', 'Answer two personal questions comfortably'], tags: ['family', 'keigo', 'high_value'] },
  { id: 's.date', title: 'デートの約束', titleEN: 'Making plans', level: 'A2', setting: 'Texting after meeting at a party.', tutorRole: 'person you met', learnerRole: 'you', learnerGoal: 'Suggest a time and place, and handle one schedule clash.', items: ['v.yoyaku', 'v.mouichido'], register: 'mixed', mustDo: ['Suggest with 〜はどうですか', 'Reschedule once'], tags: ['social', 'casual', 'speaking'] },
  { id: 's.university', title: '大学のオフィスアワー', titleEN: 'Office hours at university', level: 'B2', setting: 'Asking a professor about an essay.', tutorRole: 'professor', learnerRole: 'student', learnerGoal: 'Ask for feedback, show you understand it, and request an extension.', items: ['v.hitsuyou', 'v.kanri'], register: 'keigo', mustDo: ['Summarise the feedback back', 'Make a specific request'], tags: ['study', 'academic', 'high_value'] },
  { id: 's.kanji', title: '漢字の勉強法', titleEN: 'Talking about how you study kanji', level: 'B1', setting: 'A language-exchange meetup.', tutorRole: 'exchange partner', learnerRole: 'learner', learnerGoal: 'Explain your study method and what you find hard.', items: ['v.tokuni', 'v.muzukashii'], register: 'mixed', mustDo: ['Explain a method with 〜ています', 'Ask for their advice'], tags: ['meta', 'speaking', 'jlpt'] },
];

export const READING_PASSAGES: {
  id: string; level: CEFR; title: string; titleEN: string; text: string;
  glossary: { surface: string; reading: string; meaning: string }[];
  questions: { prompt: string; options: string[]; answer: string; explanation: string }[];
}[] = [
  {
    id: 'r.cafe', level: 'A2.1', title: 'となりの喫茶店', titleEN: 'The coffee shop next door',
    text: '駅の前に、小さな喫茶店があります。朝は七時から開いています。モーニングセットは五百円で、パンと卵とコーヒーがつきます。店の人はとても親切で、いつも「おはようございます」と笑って言います。私は毎週土曜日に、そこで本を読みます。',
    glossary: [{ surface: '喫茶店', reading: 'きっさてん', meaning: 'coffee shop' }, { surface: 'モーニングセット', reading: 'もーにんぐせっと', meaning: 'morning set' }, { surface: '親切', reading: 'しんせつ', meaning: 'kind' }],
    questions: [
      { prompt: 'その店は何時に開きますか。', options: ['六時', '七時', '八時', '十時'], answer: '七時', explanation: '「朝は七時から開いています」とあります。' },
      { prompt: 'モーニングセットに つかないものは どれですか。', options: ['パン', '卵', 'コーヒー', 'サラダ'], answer: 'サラダ', explanation: 'セットは「パンと卵とコーヒー」です。サラダは出てきません。' },
      { prompt: '「私」は いつ そこへ行きますか。', options: ['毎朝', '毎週土曜日', '日曜日の午後', '週に三回'], answer: '毎週土曜日', explanation: '「毎週土曜日に、そこで本を読みます」。' },
    ],
  },
  {
    id: 'r.keigo', level: 'B1', title: '敬語は むずかしい', titleEN: 'Keigo is hard',
    text: '日本語の敬語は、大きく分けて三つあります。相手の行動を高く言う「尊敬語」、自分の行動を低く言う「謙譲語」、そして丁寧に言う「丁寧語」です。いちばん難しいのは、相手と自分の関係によって使い分けなければならない点です。同じ「行く」でも、部長には「いらっしゃいますか」、自分には「伺います」を使います。会社の外の人と話すときは、自分の会社の人の行動にも尊敬語を使いません。',
    glossary: [{ surface: '敬語', reading: 'けいご', meaning: 'honorific language' }, { surface: '使い分ける', reading: 'つかいわける', meaning: 'to use differently by context' }, { surface: '伺う', reading: 'うかがう', meaning: 'to visit (humble)' }],
    questions: [
      { prompt: '自分が「行く」とき、謙譲語は どれですか。', options: ['行きます', 'いらっしゃいます', '伺います', '行かれます'], answer: '伺います', explanation: '謙譲語は自分の行動を低く言います。「伺う」がそれにあたります。' },
      { prompt: 'この文章によると、いちばん難しいのは どの点ですか。', options: ['漢字が多いこと', '関係によって使い分けること', '発音が難しいこと', '三つもあること'], answer: '関係によって使い分けること', explanation: '「いちばん難しいのは、相手と自分の関係によって使い分けなければならない点です」。' },
      { prompt: '社外の人と話すとき、自分の会社の人が行くと言う場合、どう言いますか。', options: ['いらっしゃいます', '伺います', '参ります', '行かれます'], answer: '伺います', explanation: '「自分の会社の人の行動にも尊敬語を使いません」→自分の側は 謙譲語の「伺う」/「参る」を使います。うちの課長が伺います。' },
    ],
  },
];

export const LISTENING_CLIPS: {
  id: string; level: CEFR; title: string; script: string;
  questions: { prompt: string; options: string[]; answer: string; explanation: string }[];
}[] = [
  {
    id: 'l.announce', level: 'A2.1', title: '駅のアナウンス', script: 'お客様にお知らせいたします。二番線の電車は、車両点検のため、十分ほど遅れております。お急ぎのお客様は、三番線の快速電車をご利用ください。よろしいでしょうか。ご迷惑をおかけして、申し訳ございません。',
    questions: [
      { prompt: '二番線の電車は どうしましたか。', options: ['運転をやめた', '十分ほど遅れている', '三番線に着いた', '速く走っている'], answer: '十分ほど遅れている', explanation: '「十分ほど遅れております」とアナウンスしています。' },
      { prompt: '急いでいる人は どうすればいいですか。', options: ['二番線で待つ', '三番線の快速に乗る', '駅員を呼ぶ', 'タクシーを使う'], answer: '三番線の快速に乗る', explanation: '「三番線の快速電車をご利用ください」と案内しています。' },
    ],
  },
  {
    id: 'l.office', level: 'B1', title: '職場の朝のやりとり', script: '部長、おはようございます。昨日の資料、確認いたしました。二ページ目の数字なのですが、少し古いようでしたので、今日の午前中に作り直してお持ちします。会議は お昼からでよろしいでしょうか。',
    questions: [
      { prompt: 'この人は これから 何をしますか。', options: ['会議に出ます', '資料を作り直します', '部長に電話します', '昼ごはんを食べます'], answer: '資料を作り直します', explanation: '「今日の午前中に作り直してお持ちします」と言っています。' },
      { prompt: '何が問題でしたか。', options: ['数字が古い', '字が小さい', 'ページが多い', '部長が不在だった'], answer: '数字が古い', explanation: '「二ページ目の数字なのですが、少し古いようでした」と伝えています。' },
    ],
  },
];

/** Onboarding probes — the placement instrument's fixed scaffolding. */
export const PLACEMENT_KANA: { kana: string; romaji: string; kind: 'hiragana' | 'katakana' }[] = [
  { kana: 'あ', romaji: 'a', kind: 'hiragana' }, { kana: 'き', romaji: 'ki', kind: 'hiragana' },
  { kana: 'し', romaji: 'shi', kind: 'hiragana' }, { kana: 'つ', romaji: 'tsu', kind: 'hiragana' },
  { kana: 'ん', romaji: 'n', kind: 'hiragana' }, { kana: 'ら', romaji: 'ra', kind: 'hiragana' },
  { kana: 'ソ', romaji: 'so', kind: 'katakana' }, { kana: 'ン', romaji: 'n', kind: 'katakana' },
  { kana: 'シ', romaji: 'shi', kind: 'katakana' }, { kana: 'ツ', romaji: 'tsu', kind: 'katakana' },
  { kana: 'ヨ', romaji: 'yo', kind: 'katakana' }, { kana: 'ヲ', romaji: 'o', kind: 'katakana' },
];

export const SPEAKING_PROBES: { id: string; level: CEFR; prompt: string; promptEN: string; expect: string }[] = [
  { id: 'sp.read1', level: 'A1', prompt: '次の文を読んでください：私は日本語を勉強しています。', promptEN: 'Read this aloud: I am studying Japanese.', expect: 'read_aloud' },
  { id: 'sp.read2', level: 'A2.1', prompt: '次の文を読んでください：昨日は雨だったので、家で本を読みました。', promptEN: 'Read aloud: Yesterday it rained, so I read at home.', expect: 'read_aloud' },
  { id: 'sp.order', level: 'A2', prompt: 'カフェで店員さんに、コーヒーとケーキを注文してください。', promptEN: 'Order a coffee and a cake at a café counter.', expect: 'transactional' },
  { id: 'sp.describe', level: 'A2.1', prompt: '週末に何をするか、三つの文で話してください。', promptEN: 'Describe what you usually do on weekends, in three sentences.', expect: 'monologue' },
  { id: 'sp.opinion', level: 'B1', prompt: '日本語を勉強するのは難しいですか。理由も教えてください。', promptEN: 'Is studying Japanese difficult? Give a reason.', expect: 'opinion' },
  { id: 'sp.keigo', level: 'B2', prompt: '会社の部長に、明日休みたいと伝えてください。', promptEN: 'Tell your department head you would like tomorrow off — politely.', expect: 'keigo' },
];

export const WRITING_PROBES: { id: string; level: CEFR; prompt: string; promptEN: string; minChars: number }[] = [
  { id: 'wr.self', level: 'A1', prompt: '自己紹介を三つ書いてください。（名前・仕事・趣味）', promptEN: 'Write three sentences introducing yourself: name, work, hobby.', minChars: 15 },
  { id: 'wr.weekend', level: 'A2.1', prompt: '先週の週末について、五つの文を書いてください。', promptEN: 'Write five sentences about last weekend.', minChars: 40 },
  { id: 'wr.email', level: 'B1', prompt: '同僚に、会議の時間を一時間遅らせたいとメールで伝えてください。', promptEN: 'Email a colleague to ask them to move a meeting one hour later.', minChars: 60 },
  { id: 'wr.opinion', level: 'B2', prompt: 'リモートワークのいい点と問題点を、両方書いてください。', promptEN: 'Write about both the good points and the problems of remote work.', minChars: 100 },
];
